// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
// Version: 2021.2.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_226_3_VITIS_LOOP_227_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        blockllr_ch_2_src_V_address0,
        blockllr_ch_2_src_V_ce0,
        blockllr_ch_2_src_V_q0,
        llr_ch_2_src_address0,
        llr_ch_2_src_ce0,
        llr_ch_2_src_we0,
        llr_ch_2_src_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] blockllr_ch_2_src_V_address0;
output   blockllr_ch_2_src_V_ce0;
input  [5:0] blockllr_ch_2_src_V_q0;
output  [11:0] llr_ch_2_src_address0;
output   llr_ch_2_src_ce0;
output   llr_ch_2_src_we0;
output  [5:0] llr_ch_2_src_d0;

reg ap_idle;
reg blockllr_ch_2_src_V_ce0;
reg llr_ch_2_src_ce0;
reg llr_ch_2_src_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln226_fu_107_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [11:0] add_ln230_fu_196_p2;
reg   [11:0] add_ln230_reg_256;
wire   [63:0] zext_ln229_fu_177_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln230_1_fu_223_p1;
reg   [7:0] q_fu_50;
wire   [7:0] add_ln227_fu_202_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_q_load;
reg   [4:0] p_fu_54;
wire   [4:0] select_ln226_1_fu_145_p3;
reg   [4:0] ap_sig_allocacmp_p_load;
reg   [11:0] indvar_flatten7_fu_58;
wire   [11:0] add_ln226_1_fu_113_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten7_load;
wire   [0:0] icmp_ln227_fu_131_p2;
wire   [4:0] add_ln226_fu_125_p2;
wire   [7:0] select_ln226_fu_137_p3;
wire   [12:0] tmp_176_fu_169_p3;
wire   [9:0] p_shl244_mid2_fu_161_p3;
wire   [9:0] q_1_cast_fu_182_p1;
wire   [9:0] add_ln230_1_fu_186_p2;
wire   [11:0] zext_ln230_fu_192_p1;
wire   [11:0] p_shl243_mid2_fu_153_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ldpcDec_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln226_fu_107_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten7_fu_58 <= add_ln226_1_fu_113_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_58 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln226_fu_107_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            p_fu_54 <= select_ln226_1_fu_145_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_54 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln226_fu_107_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            q_fu_50 <= add_ln227_fu_202_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            q_fu_50 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln226_fu_107_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln230_reg_256 <= add_ln230_fu_196_p2;
    end
end

always @ (*) begin
    if (((icmp_ln226_fu_107_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_58;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_load = 5'd0;
    end else begin
        ap_sig_allocacmp_p_load = p_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_q_load = 8'd0;
    end else begin
        ap_sig_allocacmp_q_load = q_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        blockllr_ch_2_src_V_ce0 = 1'b1;
    end else begin
        blockllr_ch_2_src_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        llr_ch_2_src_ce0 = 1'b1;
    end else begin
        llr_ch_2_src_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        llr_ch_2_src_we0 = 1'b1;
    end else begin
        llr_ch_2_src_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln226_1_fu_113_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 12'd1);

assign add_ln226_fu_125_p2 = (ap_sig_allocacmp_p_load + 5'd1);

assign add_ln227_fu_202_p2 = (select_ln226_fu_137_p3 + 8'd1);

assign add_ln230_1_fu_186_p2 = (p_shl244_mid2_fu_161_p3 + q_1_cast_fu_182_p1);

assign add_ln230_fu_196_p2 = (zext_ln230_fu_192_p1 + p_shl243_mid2_fu_153_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign blockllr_ch_2_src_V_address0 = zext_ln229_fu_177_p1;

assign icmp_ln226_fu_107_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 12'd3200) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_131_p2 = ((ap_sig_allocacmp_q_load == 8'd160) ? 1'b1 : 1'b0);

assign llr_ch_2_src_address0 = zext_ln230_1_fu_223_p1;

assign llr_ch_2_src_d0 = blockllr_ch_2_src_V_q0;

assign p_shl243_mid2_fu_153_p3 = {{select_ln226_1_fu_145_p3}, {7'd0}};

assign p_shl244_mid2_fu_161_p3 = {{select_ln226_1_fu_145_p3}, {5'd0}};

assign q_1_cast_fu_182_p1 = select_ln226_fu_137_p3;

assign select_ln226_1_fu_145_p3 = ((icmp_ln227_fu_131_p2[0:0] == 1'b1) ? add_ln226_fu_125_p2 : ap_sig_allocacmp_p_load);

assign select_ln226_fu_137_p3 = ((icmp_ln227_fu_131_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_q_load);

assign tmp_176_fu_169_p3 = {{select_ln226_1_fu_145_p3}, {select_ln226_fu_137_p3}};

assign zext_ln229_fu_177_p1 = tmp_176_fu_169_p3;

assign zext_ln230_1_fu_223_p1 = add_ln230_reg_256;

assign zext_ln230_fu_192_p1 = add_ln230_1_fu_186_p2;

endmodule //ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_226_3_VITIS_LOOP_227_4
