// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
// Version: 2021.2.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ldpcDec_ldpcDec_Pipeline_VITIS_LOOP_54_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        llr_ch_TVALID,
        llr_ch_TDATA,
        llr_ch_TREADY,
        llr_ch_2_src_V_address0,
        llr_ch_2_src_V_ce0,
        llr_ch_2_src_V_we0,
        llr_ch_2_src_V_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   llr_ch_TVALID;
input  [7:0] llr_ch_TDATA;
output   llr_ch_TREADY;
output  [11:0] llr_ch_2_src_V_address0;
output   llr_ch_2_src_V_ce0;
output   llr_ch_2_src_V_we0;
output  [5:0] llr_ch_2_src_V_d0;

reg ap_idle;
reg llr_ch_TREADY;
reg llr_ch_2_src_V_ce0;
reg llr_ch_2_src_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln54_fu_71_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    llr_ch_TDATA_blk_n;
wire   [63:0] i_9_cast_fu_83_p1;
reg   [11:0] i_fu_40;
wire   [11:0] add_ln54_fu_77_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i_3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_99;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

ldpcDec_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_99)) begin
        if ((icmp_ln54_fu_71_p2 == 1'd0)) begin
            i_fu_40 <= add_ln54_fu_77_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_40 <= 12'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (icmp_ln54_fu_71_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 12'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_40;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        llr_ch_2_src_V_ce0 = 1'b1;
    end else begin
        llr_ch_2_src_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (icmp_ln54_fu_71_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        llr_ch_2_src_V_we0 = 1'b1;
    end else begin
        llr_ch_2_src_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln54_fu_71_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        llr_ch_TDATA_blk_n = llr_ch_TVALID;
    end else begin
        llr_ch_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (icmp_ln54_fu_71_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        llr_ch_TREADY = 1'b1;
    end else begin
        llr_ch_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_fu_77_p2 = (ap_sig_allocacmp_i_3 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_99 = (~((ap_start_int == 1'b0) | ((icmp_ln54_fu_71_p2 == 1'd0) & (llr_ch_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_9_cast_fu_83_p1 = ap_sig_allocacmp_i_3;

assign icmp_ln54_fu_71_p2 = ((ap_sig_allocacmp_i_3 == 12'd3200) ? 1'b1 : 1'b0);

assign llr_ch_2_src_V_address0 = i_9_cast_fu_83_p1;

assign llr_ch_2_src_V_d0 = llr_ch_TDATA[5:0];

endmodule //ldpcDec_ldpcDec_Pipeline_VITIS_LOOP_54_5
