// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
// Version: 2021.2.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ldpcDec_colUpdate_ch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        l_address0,
        l_ce0,
        l_q0,
        l_offset,
        a_address0,
        a_ce0,
        a_we0,
        a_d0,
        a_address1,
        a_ce1,
        a_q1,
        a_offset
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] l_address0;
output   l_ce0;
input  [5:0] l_q0;
input  [3:0] l_offset;
output  [16:0] a_address0;
output   a_ce0;
output   a_we0;
output  [5:0] a_d0;
output  [16:0] a_address1;
output   a_ce1;
input  [5:0] a_q1;
input  [3:0] a_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [14:0] sub_ln534_fu_66_p2;
reg   [14:0] sub_ln534_reg_104;
wire   [14:0] sub_ln232_fu_97_p2;
reg   [14:0] sub_ln232_reg_109;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_idle;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_ready;
wire   [15:0] grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_address0;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_ce0;
wire   [16:0] grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address0;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce0;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_we0;
wire   [5:0] grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_d0;
wire   [16:0] grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address1;
wire    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce1;
reg    grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [13:0] tmp_fu_42_p3;
wire   [9:0] tmp_s_fu_54_p3;
wire   [14:0] zext_ln534_fu_50_p1;
wire   [14:0] zext_ln534_1_fu_62_p1;
wire   [13:0] tmp_185_fu_73_p3;
wire   [9:0] tmp_186_fu_85_p3;
wire   [14:0] zext_ln232_fu_81_p1;
wire   [14:0] zext_ln232_1_fu_93_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg = 1'b0;
end

ldpcDec_colUpdate_ch_Pipeline_VITIS_LOOP_531_1 grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start),
    .ap_done(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done),
    .ap_idle(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_idle),
    .ap_ready(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_ready),
    .sub_ln232(sub_ln232_reg_109),
    .l_address0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_address0),
    .l_ce0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_ce0),
    .l_q0(l_q0),
    .sub_ln534(sub_ln534_reg_104),
    .a_address0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address0),
    .a_ce0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce0),
    .a_we0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_we0),
    .a_d0(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_d0),
    .a_address1(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address1),
    .a_ce1(grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce1),
    .a_q1(a_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_ready == 1'b1)) begin
            grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln232_reg_109[14 : 6] <= sub_ln232_fu_97_p2[14 : 6];
        sub_ln534_reg_104[14 : 6] <= sub_ln534_fu_66_p2[14 : 6];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address0;

assign a_address1 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_address1;

assign a_ce0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce0;

assign a_ce1 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_ce1;

assign a_d0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_d0;

assign a_we0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_a_we0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_ap_start_reg;

assign l_address0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_address0;

assign l_ce0 = grp_colUpdate_ch_Pipeline_VITIS_LOOP_531_1_fu_32_l_ce0;

assign sub_ln232_fu_97_p2 = (zext_ln232_fu_81_p1 - zext_ln232_1_fu_93_p1);

assign sub_ln534_fu_66_p2 = (zext_ln534_fu_50_p1 - zext_ln534_1_fu_62_p1);

assign tmp_185_fu_73_p3 = {{l_offset}, {10'd0}};

assign tmp_186_fu_85_p3 = {{l_offset}, {6'd0}};

assign tmp_fu_42_p3 = {{a_offset}, {10'd0}};

assign tmp_s_fu_54_p3 = {{a_offset}, {6'd0}};

assign zext_ln232_1_fu_93_p1 = tmp_186_fu_85_p3;

assign zext_ln232_fu_81_p1 = tmp_185_fu_73_p3;

assign zext_ln534_1_fu_62_p1 = tmp_s_fu_54_p3;

assign zext_ln534_fu_50_p1 = tmp_fu_42_p3;

always @ (posedge ap_clk) begin
    sub_ln534_reg_104[5:0] <= 6'b000000;
    sub_ln232_reg_109[5:0] <= 6'b000000;
end

endmodule //ldpcDec_colUpdate_ch
