// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
// Version: 2021.2.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ldpcDec_colUpdate2_ch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        l_address0,
        l_ce0,
        l_q0,
        l_offset,
        b_address0,
        b_ce0,
        b_we0,
        b_d0,
        b_q0,
        b_address1,
        b_ce1,
        b_we1,
        b_d1,
        b_q1,
        a_offset,
        b_offset
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] l_address0;
output   l_ce0;
input  [5:0] l_q0;
input  [4:0] l_offset;
output  [16:0] b_address0;
output   b_ce0;
output   b_we0;
output  [5:0] b_d0;
input  [5:0] b_q0;
output  [16:0] b_address1;
output   b_ce1;
output   b_we1;
output  [5:0] b_d1;
input  [5:0] b_q1;
input  [4:0] a_offset;
input  [4:0] b_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] sub_ln555_fu_75_p2;
reg   [15:0] sub_ln555_reg_144;
wire   [15:0] sub_ln554_fu_106_p2;
reg   [15:0] sub_ln554_reg_149;
wire   [15:0] sub_ln232_fu_137_p2;
reg   [15:0] sub_ln232_reg_154;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_idle;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready;
wire   [15:0] grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0;
wire   [16:0] grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0;
wire   [5:0] grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0;
wire   [16:0] grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1;
wire    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1;
wire   [5:0] grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1;
reg    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [14:0] tmp_fu_51_p3;
wire   [10:0] tmp_s_fu_63_p3;
wire   [15:0] zext_ln555_fu_59_p1;
wire   [15:0] zext_ln555_1_fu_71_p1;
wire   [14:0] tmp_213_fu_82_p3;
wire   [10:0] tmp_214_fu_94_p3;
wire   [15:0] zext_ln554_fu_90_p1;
wire   [15:0] zext_ln554_1_fu_102_p1;
wire   [14:0] tmp_215_fu_113_p3;
wire   [10:0] tmp_216_fu_125_p3;
wire   [15:0] zext_ln232_fu_121_p1;
wire   [15:0] zext_ln232_13_fu_133_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg = 1'b0;
end

ldpcDec_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1 grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start),
    .ap_done(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done),
    .ap_idle(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_idle),
    .ap_ready(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready),
    .sub_ln232(sub_ln232_reg_154),
    .l_address0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0),
    .l_ce0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0),
    .l_q0(l_q0),
    .sub_ln554(sub_ln554_reg_149),
    .b_address0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0),
    .b_ce0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0),
    .b_we0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0),
    .b_d0(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0),
    .b_q0(b_q0),
    .b_address1(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1),
    .b_ce1(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1),
    .b_we1(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1),
    .b_d1(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1),
    .b_q1(b_q1),
    .sub_ln555(sub_ln555_reg_144)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready == 1'b1)) begin
            grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln232_reg_154[15 : 6] <= sub_ln232_fu_137_p2[15 : 6];
        sub_ln554_reg_149[15 : 6] <= sub_ln554_fu_106_p2[15 : 6];
        sub_ln555_reg_144[15 : 6] <= sub_ln555_fu_75_p2[15 : 6];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign b_address0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0;

assign b_address1 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1;

assign b_ce0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0;

assign b_ce1 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1;

assign b_d0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0;

assign b_d1 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1;

assign b_we0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0;

assign b_we1 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1;

assign grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg;

assign l_address0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0;

assign l_ce0 = grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0;

assign sub_ln232_fu_137_p2 = (zext_ln232_fu_121_p1 - zext_ln232_13_fu_133_p1);

assign sub_ln554_fu_106_p2 = (zext_ln554_fu_90_p1 - zext_ln554_1_fu_102_p1);

assign sub_ln555_fu_75_p2 = (zext_ln555_fu_59_p1 - zext_ln555_1_fu_71_p1);

assign tmp_213_fu_82_p3 = {{a_offset}, {10'd0}};

assign tmp_214_fu_94_p3 = {{a_offset}, {6'd0}};

assign tmp_215_fu_113_p3 = {{l_offset}, {10'd0}};

assign tmp_216_fu_125_p3 = {{l_offset}, {6'd0}};

assign tmp_fu_51_p3 = {{b_offset}, {10'd0}};

assign tmp_s_fu_63_p3 = {{b_offset}, {6'd0}};

assign zext_ln232_13_fu_133_p1 = tmp_216_fu_125_p3;

assign zext_ln232_fu_121_p1 = tmp_215_fu_113_p3;

assign zext_ln554_1_fu_102_p1 = tmp_214_fu_94_p3;

assign zext_ln554_fu_90_p1 = tmp_213_fu_82_p3;

assign zext_ln555_1_fu_71_p1 = tmp_s_fu_63_p3;

assign zext_ln555_fu_59_p1 = tmp_fu_51_p3;

always @ (posedge ap_clk) begin
    sub_ln555_reg_144[5:0] <= 6'b000000;
    sub_ln554_reg_149[5:0] <= 6'b000000;
    sub_ln232_reg_154[5:0] <= 6'b000000;
end

endmodule //ldpcDec_colUpdate2_ch
