// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
// Version: 2021.2.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ldpcDec_colUpdate3_Pipeline_VITIS_LOOP_764_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sub_ln783,
        r_address0,
        r_ce0,
        r_we0,
        r_d0,
        sub_ln232,
        l_address0,
        l_ce0,
        l_q0,
        sub_ln767,
        c_address0,
        c_ce0,
        c_we0,
        c_d0,
        c_q0,
        c_address1,
        c_ce1,
        c_we1,
        c_d1,
        c_q1,
        sub_ln768,
        sub_ln769
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] sub_ln783;
output  [15:0] r_address0;
output   r_ce0;
output   r_we0;
output  [0:0] r_d0;
input  [15:0] sub_ln232;
output  [15:0] l_address0;
output   l_ce0;
input  [5:0] l_q0;
input  [18:0] sub_ln767;
output  [18:0] c_address0;
output   c_ce0;
output   c_we0;
output  [5:0] c_d0;
input  [5:0] c_q0;
output  [18:0] c_address1;
output   c_ce1;
output   c_we1;
output  [5:0] c_d1;
input  [5:0] c_q1;
input  [18:0] sub_ln768;
input  [18:0] sub_ln769;

reg ap_idle;
reg r_ce0;
reg r_we0;
reg l_ce0;
reg[18:0] c_address0;
reg c_ce0;
reg c_we0;
reg[5:0] c_d0;
reg[18:0] c_address1;
reg c_ce1;
reg c_we1;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln764_reg_306;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln764_fu_151_p2;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln783_fu_171_p2;
reg   [15:0] add_ln783_reg_310;
reg   [18:0] c_addr_reg_320;
reg   [18:0] c_addr_1_reg_325;
reg   [18:0] c_addr_1_reg_325_pp0_iter1_reg;
wire   [18:0] add_ln769_fu_210_p2;
reg   [18:0] add_ln769_reg_330;
reg   [18:0] c_addr_2_reg_335;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
reg   [18:0] c_addr_2_reg_335_pp0_iter1_reg;
reg  signed [5:0] rhs_reg_341;
reg  signed [5:0] rhs_7_reg_348;
reg  signed [5:0] lhs_reg_355;
wire   [5:0] add_ln1540_fu_262_p2;
reg   [5:0] add_ln1540_reg_361;
wire    ap_block_pp0_stage2_11001;
wire   [5:0] sub_ln70_1_fu_285_p2;
reg   [5:0] sub_ln70_1_reg_366;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln232_fu_183_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln767_fu_194_p1;
wire   [63:0] zext_ln768_fu_205_p1;
wire   [63:0] zext_ln769_fu_221_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln783_2_fu_225_p1;
wire    ap_block_pp0_stage2;
reg   [7:0] i_fu_50;
wire   [7:0] add_ln764_fu_157_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_10;
wire   [15:0] zext_ln783_1_fu_167_p1;
wire   [15:0] add_ln232_fu_177_p2;
wire   [18:0] zext_ln783_fu_163_p1;
wire   [18:0] add_ln767_fu_188_p2;
wire   [18:0] add_ln768_fu_199_p2;
wire  signed [6:0] sext_ln232_fu_229_p1;
wire  signed [6:0] sext_ln232_29_fu_232_p1;
wire   [6:0] ret_fu_235_p2;
wire  signed [7:0] sext_ln232_30_fu_241_p1;
wire  signed [7:0] sext_ln232_31_fu_245_p1;
wire  signed [5:0] sext_ln1540_fu_254_p0;
wire   [5:0] add_ln1540_46_fu_258_p2;
wire   [7:0] ret_8_fu_248_p2;
wire  signed [7:0] sext_ln1540_fu_254_p1;
wire  signed [5:0] add_ln1541_fu_273_p0;
wire   [5:0] add_ln1541_fu_273_p2;
wire   [7:0] ret_9_fu_267_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

ldpcDec_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln764_fu_151_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_50 <= add_ln764_fu_157_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_50 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln764_reg_306 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln1540_reg_361 <= add_ln1540_fu_262_p2;
        sub_ln70_1_reg_366 <= sub_ln70_1_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln764_fu_151_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln769_reg_330 <= add_ln769_fu_210_p2;
        add_ln783_reg_310 <= add_ln783_fu_171_p2;
        c_addr_1_reg_325 <= zext_ln768_fu_205_p1;
        c_addr_reg_320 <= zext_ln767_fu_194_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_addr_1_reg_325_pp0_iter1_reg <= c_addr_1_reg_325;
        icmp_ln764_reg_306 <= icmp_ln764_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln764_reg_306 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_addr_2_reg_335 <= zext_ln769_fu_221_p1;
        lhs_reg_355 <= l_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_addr_2_reg_335_pp0_iter1_reg <= c_addr_2_reg_335;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln764_reg_306 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        rhs_7_reg_348 <= c_q0;
        rhs_reg_341 <= c_q1;
    end
end

always @ (*) begin
    if (((icmp_ln764_reg_306 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_10 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_10 = i_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        c_address0 = c_addr_2_reg_335_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_address0 = c_addr_1_reg_325_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_address0 = zext_ln768_fu_205_p1;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            c_address1 = c_addr_reg_320;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            c_address1 = zext_ln769_fu_221_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_address1 = zext_ln767_fu_194_p1;
        end else begin
            c_address1 = 'bx;
        end
    end else begin
        c_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        c_ce1 = 1'b1;
    end else begin
        c_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            c_d0 = add_ln1540_reg_361;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            c_d0 = sub_ln70_1_reg_366;
        end else begin
            c_d0 = 'bx;
        end
    end else begin
        c_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        c_we0 = 1'b1;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln764_reg_306 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        c_we1 = 1'b1;
    end else begin
        c_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        l_ce0 = 1'b1;
    end else begin
        l_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        r_ce0 = 1'b1;
    end else begin
        r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln764_reg_306 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        r_we0 = 1'b1;
    end else begin
        r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1540_46_fu_258_p2 = ($signed(rhs_reg_341) + $signed(rhs_7_reg_348));

assign add_ln1540_fu_262_p2 = ($signed(add_ln1540_46_fu_258_p2) + $signed(lhs_reg_355));

assign add_ln1541_fu_273_p0 = c_q1;

assign add_ln1541_fu_273_p2 = ($signed(add_ln1541_fu_273_p0) + $signed(add_ln1540_fu_262_p2));

assign add_ln232_fu_177_p2 = (sub_ln232 + zext_ln783_1_fu_167_p1);

assign add_ln764_fu_157_p2 = (ap_sig_allocacmp_i_10 + 8'd1);

assign add_ln767_fu_188_p2 = (sub_ln767 + zext_ln783_fu_163_p1);

assign add_ln768_fu_199_p2 = (sub_ln768 + zext_ln783_fu_163_p1);

assign add_ln769_fu_210_p2 = (sub_ln769 + zext_ln783_fu_163_p1);

assign add_ln783_fu_171_p2 = (sub_ln783 + zext_ln783_1_fu_167_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign c_d1 = ($signed(add_ln1541_fu_273_p2) - $signed(rhs_reg_341));

assign icmp_ln764_fu_151_p2 = ((ap_sig_allocacmp_i_10 == 8'd160) ? 1'b1 : 1'b0);

assign l_address0 = zext_ln232_fu_183_p1;

assign r_address0 = zext_ln783_2_fu_225_p1;

assign r_d0 = ret_9_fu_267_p2[32'd7];

assign ret_8_fu_248_p2 = ($signed(sext_ln232_30_fu_241_p1) + $signed(sext_ln232_31_fu_245_p1));

assign ret_9_fu_267_p2 = ($signed(ret_8_fu_248_p2) + $signed(sext_ln1540_fu_254_p1));

assign ret_fu_235_p2 = ($signed(sext_ln232_fu_229_p1) + $signed(sext_ln232_29_fu_232_p1));

assign sext_ln1540_fu_254_p0 = c_q1;

assign sext_ln1540_fu_254_p1 = sext_ln1540_fu_254_p0;

assign sext_ln232_29_fu_232_p1 = rhs_reg_341;

assign sext_ln232_30_fu_241_p1 = $signed(ret_fu_235_p2);

assign sext_ln232_31_fu_245_p1 = rhs_7_reg_348;

assign sext_ln232_fu_229_p1 = lhs_reg_355;

assign sub_ln70_1_fu_285_p2 = ($signed(add_ln1541_fu_273_p2) - $signed(rhs_7_reg_348));

assign zext_ln232_fu_183_p1 = add_ln232_fu_177_p2;

assign zext_ln767_fu_194_p1 = add_ln767_fu_188_p2;

assign zext_ln768_fu_205_p1 = add_ln768_fu_199_p2;

assign zext_ln769_fu_221_p1 = add_ln769_reg_330;

assign zext_ln783_1_fu_167_p1 = ap_sig_allocacmp_i_10;

assign zext_ln783_2_fu_225_p1 = add_ln783_reg_310;

assign zext_ln783_fu_163_p1 = ap_sig_allocacmp_i_10;

endmodule //ldpcDec_colUpdate3_Pipeline_VITIS_LOOP_764_1
