-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
-- Version: 2021.2.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_572_113 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    minfo_ch_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    minfo_ch_ce0 : OUT STD_LOGIC;
    minfo_ch_we0 : OUT STD_LOGIC;
    minfo_ch_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    minfo_ch_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    minfo_ch_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    minfo_ch_ce1 : OUT STD_LOGIC;
    minfo_ch_we1 : OUT STD_LOGIC;
    minfo_ch_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    minfo_ch_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
    blockllr_ch_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    blockllr_ch_ce0 : OUT STD_LOGIC;
    blockllr_ch_q0 : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_572_113 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv15_55C0 : STD_LOGIC_VECTOR (14 downto 0) := "101010111000000";
    constant ap_const_lv15_5980 : STD_LOGIC_VECTOR (14 downto 0) := "101100110000000";
    constant ap_const_lv14_2540 : STD_LOGIC_VECTOR (13 downto 0) := "10010101000000";
    constant ap_const_lv15_5D40 : STD_LOGIC_VECTOR (14 downto 0) := "101110101000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_1F : STD_LOGIC_VECTOR (7 downto 0) := "00011111";
    constant ap_const_lv8_E0 : STD_LOGIC_VECTOR (7 downto 0) := "11100000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_1F : STD_LOGIC_VECTOR (8 downto 0) := "000011111";
    constant ap_const_lv9_1E0 : STD_LOGIC_VECTOR (8 downto 0) := "111100000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln572_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal zext_ln575_1_fu_136_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln575_1_reg_402 : STD_LOGIC_VECTOR (14 downto 0);
    signal minfo_ch_addr_reg_407 : STD_LOGIC_VECTOR (16 downto 0);
    signal minfo_ch_addr_1_reg_413 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal rhs_reg_429 : STD_LOGIC_VECTOR (5 downto 0);
    signal rhs_1_reg_434 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_1_fu_226_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_1_reg_439 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln575_2_fu_150_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln576_fu_165_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln232_fu_180_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln577_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_62 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln572_fu_126_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln70_2_fu_266_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln70_fu_370_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln575_fu_140_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln575_fu_146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln576_fu_155_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln576_fu_161_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln575_fu_132_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln232_fu_170_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln232_fu_176_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln577_fu_190_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln577_fu_195_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln232_5_fu_208_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln232_4_fu_204_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln232_5_fu_208_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_fu_212_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln232_7_fu_222_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln232_6_fu_218_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln232_7_fu_222_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_232_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln1080_2_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln583_2_fu_248_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1072_2_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_2_fu_262_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1540_fu_275_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1540_fu_275_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1540_fu_282_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln70_fu_287_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1541_fu_279_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln70_fu_291_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_297_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1080_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln583_fu_313_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1541_1_fu_327_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln70_1_fu_330_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_336_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1080_1_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln583_1_fu_352_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln1072_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_fu_366_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1072_1_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_1_fu_379_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldpcDec_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ldpcDec_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln572_fu_120_p2 = ap_const_lv1_0)) then 
                    i_fu_62 <= add_ln572_fu_126_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_62 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (icmp_ln572_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    minfo_ch_addr_1_reg_413(15 downto 0) <= zext_ln576_fu_165_p1(17 - 1 downto 0)(15 downto 0);
                    minfo_ch_addr_reg_407(15 downto 0) <= zext_ln575_2_fu_150_p1(17 - 1 downto 0)(15 downto 0);
                    zext_ln575_1_reg_402(7 downto 0) <= zext_ln575_1_fu_136_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                ret_1_reg_439 <= ret_1_fu_226_p2;
                rhs_1_reg_434 <= minfo_ch_q0;
                rhs_reg_429 <= minfo_ch_q1;
            end if;
        end if;
    end process;
    zext_ln575_1_reg_402(14 downto 8) <= "0000000";
    minfo_ch_addr_reg_407(16) <= '0';
    minfo_ch_addr_1_reg_413(16) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start_int = ap_const_logic_1) and (icmp_ln572_fu_120_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln1540_fu_282_p2 <= std_logic_vector(unsigned(ret_1_reg_439) + unsigned(sext_ln1540_fu_275_p1));
    add_ln232_fu_170_p2 <= std_logic_vector(unsigned(zext_ln575_fu_132_p1) + unsigned(ap_const_lv14_2540));
    add_ln572_fu_126_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv8_1));
    add_ln575_fu_140_p2 <= std_logic_vector(unsigned(zext_ln575_1_fu_136_p1) + unsigned(ap_const_lv15_55C0));
    add_ln576_fu_155_p2 <= std_logic_vector(unsigned(zext_ln575_1_fu_136_p1) + unsigned(ap_const_lv15_5980));
    add_ln577_fu_190_p2 <= std_logic_vector(unsigned(zext_ln575_1_reg_402) + unsigned(ap_const_lv15_5D40));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln572_fu_120_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_state1, i_fu_62, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_62;
        end if; 
    end process;

    blockllr_ch_address0 <= zext_ln232_fu_180_p1(16 - 1 downto 0);

    blockllr_ch_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            blockllr_ch_ce0 <= ap_const_logic_1;
        else 
            blockllr_ch_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1072_1_fu_360_p2 <= "1" when (signed(select_ln583_1_fu_352_p3) < signed(ap_const_lv9_1E0)) else "0";
    icmp_ln1072_2_fu_256_p2 <= "1" when (signed(select_ln583_2_fu_248_p3) < signed(ap_const_lv8_E0)) else "0";
    icmp_ln1072_fu_321_p2 <= "1" when (signed(select_ln583_fu_313_p3) < signed(ap_const_lv9_1E0)) else "0";
    icmp_ln1080_1_fu_346_p2 <= "1" when (signed(tmp_1_fu_336_p4) > signed(ap_const_lv4_0)) else "0";
    icmp_ln1080_2_fu_242_p2 <= "1" when (signed(tmp_2_fu_232_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln1080_fu_307_p2 <= "1" when (signed(tmp_fu_297_p4) > signed(ap_const_lv4_0)) else "0";
    icmp_ln572_fu_120_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv8_A0) else "0";

    minfo_ch_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_CS_fsm_state3, minfo_ch_addr_reg_407, ap_CS_fsm_state2, zext_ln576_fu_165_p1, zext_ln577_fu_199_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            minfo_ch_address0 <= minfo_ch_addr_reg_407;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            minfo_ch_address0 <= zext_ln577_fu_199_p1(17 - 1 downto 0);
        elsif (((icmp_ln572_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            minfo_ch_address0 <= zext_ln576_fu_165_p1(17 - 1 downto 0);
        else 
            minfo_ch_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    minfo_ch_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_CS_fsm_state3, minfo_ch_addr_1_reg_413, zext_ln575_2_fu_150_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            minfo_ch_address1 <= minfo_ch_addr_1_reg_413;
        elsif (((icmp_ln572_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            minfo_ch_address1 <= zext_ln575_2_fu_150_p1(17 - 1 downto 0);
        else 
            minfo_ch_address1 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    minfo_ch_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_CS_fsm_state3, ap_CS_fsm_state2, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start_int = ap_const_logic_1) and (icmp_ln572_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            minfo_ch_ce0 <= ap_const_logic_1;
        else 
            minfo_ch_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    minfo_ch_ce1_assign_proc : process(ap_CS_fsm_state1, icmp_ln572_fu_120_p2, ap_CS_fsm_state3, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start_int = ap_const_logic_1) and (icmp_ln572_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            minfo_ch_ce1 <= ap_const_logic_1;
        else 
            minfo_ch_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    minfo_ch_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state2, select_ln70_2_fu_266_p3, select_ln70_fu_370_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            minfo_ch_d0 <= select_ln70_fu_370_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            minfo_ch_d0 <= select_ln70_2_fu_266_p3;
        else 
            minfo_ch_d0 <= "XXXXXX";
        end if; 
    end process;

    minfo_ch_d1 <= 
        ap_const_lv6_20 when (icmp_ln1072_1_fu_360_p2(0) = '1') else 
        trunc_ln70_1_fu_379_p1;

    minfo_ch_we0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            minfo_ch_we0 <= ap_const_logic_1;
        else 
            minfo_ch_we0 <= ap_const_logic_0;
        end if; 
    end process;


    minfo_ch_we1_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            minfo_ch_we1 <= ap_const_logic_1;
        else 
            minfo_ch_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ret_1_fu_226_p2 <= std_logic_vector(signed(sext_ln232_6_fu_218_p1) + signed(sext_ln232_7_fu_222_p1));
    ret_fu_212_p2 <= std_logic_vector(signed(sext_ln232_4_fu_204_p1) + signed(sext_ln232_5_fu_208_p1));
    select_ln583_1_fu_352_p3 <= 
        ap_const_lv9_1F when (icmp_ln1080_1_fu_346_p2(0) = '1') else 
        sub_ln70_1_fu_330_p2;
    select_ln583_2_fu_248_p3 <= 
        ap_const_lv8_1F when (icmp_ln1080_2_fu_242_p2(0) = '1') else 
        ret_1_fu_226_p2;
    select_ln583_fu_313_p3 <= 
        ap_const_lv9_1F when (icmp_ln1080_fu_307_p2(0) = '1') else 
        sub_ln70_fu_291_p2;
    select_ln70_2_fu_266_p3 <= 
        ap_const_lv6_20 when (icmp_ln1072_2_fu_256_p2(0) = '1') else 
        trunc_ln70_2_fu_262_p1;
    select_ln70_fu_370_p3 <= 
        ap_const_lv6_20 when (icmp_ln1072_fu_321_p2(0) = '1') else 
        trunc_ln70_fu_366_p1;
    sext_ln1540_fu_275_p0 <= minfo_ch_q0;
        sext_ln1540_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1540_fu_275_p0),8));

        sext_ln1541_1_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_1_reg_434),9));

        sext_ln1541_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_reg_429),9));

        sext_ln232_4_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(blockllr_ch_q0),7));

    sext_ln232_5_fu_208_p0 <= minfo_ch_q1;
        sext_ln232_5_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln232_5_fu_208_p0),7));

        sext_ln232_6_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_fu_212_p2),8));

    sext_ln232_7_fu_222_p0 <= minfo_ch_q0;
        sext_ln232_7_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln232_7_fu_222_p0),8));

        sext_ln232_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln232_fu_170_p2),15));

        sext_ln575_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln575_fu_140_p2),16));

        sext_ln576_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln576_fu_155_p2),16));

        sext_ln577_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln577_fu_190_p2),16));

        sext_ln70_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1540_fu_282_p2),9));

    sub_ln70_1_fu_330_p2 <= std_logic_vector(signed(sext_ln70_fu_287_p1) - signed(sext_ln1541_1_fu_327_p1));
    sub_ln70_fu_291_p2 <= std_logic_vector(signed(sext_ln70_fu_287_p1) - signed(sext_ln1541_fu_279_p1));
    tmp_1_fu_336_p4 <= sub_ln70_1_fu_330_p2(8 downto 5);
    tmp_2_fu_232_p4 <= ret_1_fu_226_p2(7 downto 5);
    tmp_fu_297_p4 <= sub_ln70_fu_291_p2(8 downto 5);
    trunc_ln70_1_fu_379_p1 <= select_ln583_1_fu_352_p3(6 - 1 downto 0);
    trunc_ln70_2_fu_262_p1 <= select_ln583_2_fu_248_p3(6 - 1 downto 0);
    trunc_ln70_fu_366_p1 <= select_ln583_fu_313_p3(6 - 1 downto 0);
    zext_ln232_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln232_fu_176_p1),64));
    zext_ln575_1_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),15));
    zext_ln575_2_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln575_fu_146_p1),64));
    zext_ln575_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),14));
    zext_ln576_fu_165_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln576_fu_161_p1),64));
    zext_ln577_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln577_fu_195_p1),64));
end behav;
