-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
-- Version: 2021.2.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    blockllr_src_2_ch_V_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    blockllr_src_2_ch_V_ce0 : OUT STD_LOGIC;
    blockllr_src_2_ch_V_we0 : OUT STD_LOGIC;
    blockllr_src_2_ch_V_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    llr_src_2_ch_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    llr_src_2_ch_ce0 : OUT STD_LOGIC;
    llr_src_2_ch_q0 : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of ldpcDec_updateChMinfo_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_C80 : STD_LOGIC_VECTOR (11 downto 0) := "110010000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln142_fu_113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln142_fu_143_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln142_reg_283 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln142_1_fu_151_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln142_1_reg_288 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln146_1_fu_195_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln146_4_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal q_fu_56 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln143_fu_200_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_q_load : STD_LOGIC_VECTOR (7 downto 0);
    signal p_fu_60 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_p_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_64 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln142_1_fu_119_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln143_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln142_fu_131_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl215_mid2_fu_167_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_cast_fu_175_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln146_1_fu_179_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln146_fu_185_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_mid2_fu_159_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln146_fu_189_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_84_fu_228_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_221_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln146_2_fu_235_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln146_fu_239_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln146_3_fu_245_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln146_2_fu_248_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldpcDec_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ldpcDec_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln142_fu_113_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_64 <= add_ln142_1_fu_119_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_64 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    p_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln142_fu_113_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    p_fu_60 <= select_ln142_1_fu_151_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_60 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    q_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln142_fu_113_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    q_fu_56 <= add_ln143_fu_200_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    q_fu_56 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln142_fu_113_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln142_1_reg_288 <= select_ln142_1_fu_151_p3;
                select_ln142_reg_283 <= select_ln142_fu_143_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln142_1_fu_119_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv12_1));
    add_ln142_fu_131_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_load) + unsigned(ap_const_lv5_1));
    add_ln143_fu_200_p2 <= std_logic_vector(unsigned(select_ln142_fu_143_p3) + unsigned(ap_const_lv8_1));
    add_ln146_1_fu_179_p2 <= std_logic_vector(unsigned(p_shl215_mid2_fu_167_p3) + unsigned(q_cast_fu_175_p1));
    add_ln146_2_fu_248_p2 <= std_logic_vector(unsigned(sub_ln146_fu_239_p2) + unsigned(zext_ln146_3_fu_245_p1));
    add_ln146_fu_189_p2 <= std_logic_vector(unsigned(zext_ln146_fu_185_p1) + unsigned(p_shl_mid2_fu_159_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln142_fu_113_p2)
    begin
        if (((icmp_ln142_fu_113_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_64)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_64;
        end if; 
    end process;


    ap_sig_allocacmp_p_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, p_fu_60)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_p_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_p_load <= p_fu_60;
        end if; 
    end process;


    ap_sig_allocacmp_q_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, q_fu_56, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_q_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_q_load <= q_fu_56;
        end if; 
    end process;

    blockllr_src_2_ch_V_address0 <= zext_ln146_4_fu_254_p1(15 - 1 downto 0);

    blockllr_src_2_ch_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            blockllr_src_2_ch_V_ce0 <= ap_const_logic_1;
        else 
            blockllr_src_2_ch_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blockllr_src_2_ch_V_d0 <= llr_src_2_ch_q0;

    blockllr_src_2_ch_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            blockllr_src_2_ch_V_we0 <= ap_const_logic_1;
        else 
            blockllr_src_2_ch_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln142_fu_113_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv12_C80) else "0";
    icmp_ln143_fu_137_p2 <= "1" when (ap_sig_allocacmp_q_load = ap_const_lv8_A0) else "0";
    llr_src_2_ch_address0 <= zext_ln146_1_fu_195_p1(12 - 1 downto 0);

    llr_src_2_ch_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            llr_src_2_ch_ce0 <= ap_const_logic_1;
        else 
            llr_src_2_ch_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl215_mid2_fu_167_p3 <= (select_ln142_1_fu_151_p3 & ap_const_lv5_0);
    p_shl_mid2_fu_159_p3 <= (select_ln142_1_fu_151_p3 & ap_const_lv7_0);
    q_cast_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln142_fu_143_p3),10));
    select_ln142_1_fu_151_p3 <= 
        add_ln142_fu_131_p2 when (icmp_ln143_fu_137_p2(0) = '1') else 
        ap_sig_allocacmp_p_load;
    select_ln142_fu_143_p3 <= 
        ap_const_lv8_0 when (icmp_ln143_fu_137_p2(0) = '1') else 
        ap_sig_allocacmp_q_load;
    sub_ln146_fu_239_p2 <= std_logic_vector(unsigned(tmp_fu_221_p3) - unsigned(zext_ln146_2_fu_235_p1));
    tmp_84_fu_228_p3 <= (select_ln142_1_reg_288 & ap_const_lv6_0);
    tmp_fu_221_p3 <= (select_ln142_1_reg_288 & ap_const_lv10_0);
    zext_ln146_1_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_fu_189_p2),64));
    zext_ln146_2_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_84_fu_228_p3),15));
    zext_ln146_3_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln142_reg_283),15));
    zext_ln146_4_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_2_fu_248_p2),64));
    zext_ln146_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_1_fu_179_p2),12));
end behav;
