-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
-- Version: 2021.2.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldpcDec_colUpdate3_I_ch3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    l_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    l_ce0 : OUT STD_LOGIC;
    l_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    l_offset : IN STD_LOGIC_VECTOR (5 downto 0);
    blk_i_s2c_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    blk_i_s2c_ce0 : OUT STD_LOGIC;
    blk_i_s2c_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    blk_i_s2c_offset : IN STD_LOGIC_VECTOR (4 downto 0);
    blk_i_c2s_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    blk_i_c2s_ce0 : OUT STD_LOGIC;
    blk_i_c2s_we0 : OUT STD_LOGIC;
    blk_i_c2s_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    blk_i_c2s_offset : IN STD_LOGIC_VECTOR (4 downto 0);
    c_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    c_ce0 : OUT STD_LOGIC;
    c_we0 : OUT STD_LOGIC;
    c_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    c_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    c_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    c_ce1 : OUT STD_LOGIC;
    c_we1 : OUT STD_LOGIC;
    c_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    c_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
    a_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    b_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    c_offset : IN STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of ldpcDec_colUpdate3_I_ch3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sub_ln509_fu_118_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln509_reg_260 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln508_fu_145_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln508_reg_265 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln507_fu_172_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln507_reg_270 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln524_fu_199_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln524_reg_275 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln232_fu_226_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln232_reg_280 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln232_1_fu_253_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln232_1_reg_285 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_idle : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_ready : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_ce0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_ce0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_ce0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_we0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we0 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce1 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we1 : STD_LOGIC;
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_106_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_98_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln509_fu_114_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_196_fu_133_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_195_fu_125_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln508_fu_141_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_198_fu_160_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_197_fu_152_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln507_fu_168_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_200_fu_187_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_199_fu_179_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln524_fu_195_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_202_fu_214_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_201_fu_206_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln232_fu_222_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_204_fu_241_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_203_fu_233_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln232_9_fu_249_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldpcDec_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sub_ln232_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        l_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        l_ce0 : OUT STD_LOGIC;
        l_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        sub_ln232 : IN STD_LOGIC_VECTOR (14 downto 0);
        blk_i_s2c_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        blk_i_s2c_ce0 : OUT STD_LOGIC;
        blk_i_s2c_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        sub_ln524 : IN STD_LOGIC_VECTOR (14 downto 0);
        blk_i_c2s_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        blk_i_c2s_ce0 : OUT STD_LOGIC;
        blk_i_c2s_we0 : OUT STD_LOGIC;
        blk_i_c2s_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        sub_ln507 : IN STD_LOGIC_VECTOR (16 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_we0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        c_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        c_ce1 : OUT STD_LOGIC;
        c_we1 : OUT STD_LOGIC;
        c_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
        sub_ln508 : IN STD_LOGIC_VECTOR (16 downto 0);
        sub_ln509 : IN STD_LOGIC_VECTOR (16 downto 0) );
    end component;



begin
    grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80 : component ldpcDec_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start,
        ap_done => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done,
        ap_idle => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_idle,
        ap_ready => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_ready,
        sub_ln232_1 => sub_ln232_1_reg_285,
        l_address0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_address0,
        l_ce0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_ce0,
        l_q0 => l_q0,
        sub_ln232 => sub_ln232_reg_280,
        blk_i_s2c_address0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_address0,
        blk_i_s2c_ce0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_ce0,
        blk_i_s2c_q0 => blk_i_s2c_q0,
        sub_ln524 => sub_ln524_reg_275,
        blk_i_c2s_address0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_address0,
        blk_i_c2s_ce0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_ce0,
        blk_i_c2s_we0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_we0,
        blk_i_c2s_d0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_d0,
        sub_ln507 => sub_ln507_reg_270,
        c_address0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address0,
        c_ce0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce0,
        c_we0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we0,
        c_d0 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d0,
        c_q0 => c_q0,
        c_address1 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address1,
        c_ce1 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce1,
        c_we1 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we1,
        c_d1 => grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d1,
        c_q1 => c_q1,
        sub_ln508 => sub_ln508_reg_265,
        sub_ln509 => sub_ln509_reg_260);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_ready = ap_const_logic_1)) then 
                    grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    sub_ln232_1_reg_285(15 downto 6) <= sub_ln232_1_fu_253_p2(15 downto 6);
                    sub_ln232_reg_280(14 downto 6) <= sub_ln232_fu_226_p2(14 downto 6);
                    sub_ln507_reg_270(16 downto 6) <= sub_ln507_fu_172_p2(16 downto 6);
                    sub_ln508_reg_265(16 downto 6) <= sub_ln508_fu_145_p2(16 downto 6);
                    sub_ln509_reg_260(16 downto 6) <= sub_ln509_fu_118_p2(16 downto 6);
                    sub_ln524_reg_275(14 downto 6) <= sub_ln524_fu_199_p2(14 downto 6);
            end if;
        end if;
    end process;
    sub_ln509_reg_260(5 downto 0) <= "000000";
    sub_ln508_reg_265(5 downto 0) <= "000000";
    sub_ln507_reg_270(5 downto 0) <= "000000";
    sub_ln524_reg_275(5 downto 0) <= "000000";
    sub_ln232_reg_280(5 downto 0) <= "000000";
    sub_ln232_1_reg_285(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done)
    begin
        if ((grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    blk_i_c2s_address0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_address0;
    blk_i_c2s_ce0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_ce0;
    blk_i_c2s_d0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_d0;
    blk_i_c2s_we0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_c2s_we0;
    blk_i_s2c_address0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_address0;
    blk_i_s2c_ce0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_blk_i_s2c_ce0;
    c_address0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address0;
    c_address1 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_address1;
    c_ce0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce0;
    c_ce1 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_ce1;
    c_d0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d0;
    c_d1 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_d1;
    c_we0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we0;
    c_we1 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_c_we1;
    grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_ap_start_reg;
    l_address0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_address0;
    l_ce0 <= grp_colUpdate3_I_ch3_Pipeline_VITIS_LOOP_504_1_fu_80_l_ce0;
    sub_ln232_1_fu_253_p2 <= std_logic_vector(unsigned(tmp_203_fu_233_p3) - unsigned(zext_ln232_9_fu_249_p1));
    sub_ln232_fu_226_p2 <= std_logic_vector(unsigned(tmp_201_fu_206_p3) - unsigned(zext_ln232_fu_222_p1));
    sub_ln507_fu_172_p2 <= std_logic_vector(unsigned(tmp_197_fu_152_p3) - unsigned(zext_ln507_fu_168_p1));
    sub_ln508_fu_145_p2 <= std_logic_vector(unsigned(tmp_195_fu_125_p3) - unsigned(zext_ln508_fu_141_p1));
    sub_ln509_fu_118_p2 <= std_logic_vector(unsigned(tmp_fu_98_p3) - unsigned(zext_ln509_fu_114_p1));
    sub_ln524_fu_199_p2 <= std_logic_vector(unsigned(tmp_199_fu_179_p3) - unsigned(zext_ln524_fu_195_p1));
    tmp_195_fu_125_p3 <= (b_offset & ap_const_lv10_0);
    tmp_196_fu_133_p3 <= (b_offset & ap_const_lv6_0);
    tmp_197_fu_152_p3 <= (a_offset & ap_const_lv10_0);
    tmp_198_fu_160_p3 <= (a_offset & ap_const_lv6_0);
    tmp_199_fu_179_p3 <= (blk_i_c2s_offset & ap_const_lv10_0);
    tmp_200_fu_187_p3 <= (blk_i_c2s_offset & ap_const_lv6_0);
    tmp_201_fu_206_p3 <= (blk_i_s2c_offset & ap_const_lv10_0);
    tmp_202_fu_214_p3 <= (blk_i_s2c_offset & ap_const_lv6_0);
    tmp_203_fu_233_p3 <= (l_offset & ap_const_lv10_0);
    tmp_204_fu_241_p3 <= (l_offset & ap_const_lv6_0);
    tmp_fu_98_p3 <= (c_offset & ap_const_lv10_0);
    tmp_s_fu_106_p3 <= (c_offset & ap_const_lv6_0);
    zext_ln232_9_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_204_fu_241_p3),16));
    zext_ln232_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_202_fu_214_p3),15));
    zext_ln507_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_198_fu_160_p3),17));
    zext_ln508_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_196_fu_133_p3),17));
    zext_ln509_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_106_p3),17));
    zext_ln524_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_200_fu_187_p3),15));
end behav;
