-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
-- Version: 2021.2.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldpcDec_atanh_signed is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (5 downto 0);
    b : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of ldpcDec_atanh_signed is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal atanh_table_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal atanh_table_V_ce0 : STD_LOGIC;
    signal atanh_table_V_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal atanh_table_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal atanh_table_V_ce1 : STD_LOGIC;
    signal atanh_table_V_q1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_63_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_22_fu_77_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_210 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln82_fu_139_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln232_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1072_fu_59_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln1072_fu_91_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_97_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_b_V_fu_85_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal abs_a_V_fu_71_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln365_fu_113_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal abs_b_V_1_fu_105_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_121_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln82_fu_129_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln82_fu_133_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln1072_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1072_1_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_b_V_2_fu_156_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln232_fu_164_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln232_fu_168_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_fu_183_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal xor_ln1072_1_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln70_fu_187_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln1072_fu_179_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_reset_start_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldpcDec_atanh_signed_atanh_table_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    atanh_table_V_U : component ldpcDec_atanh_signed_atanh_table_V_ROM_AUTO_1R
    generic map (
        DataWidth => 5,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => atanh_table_V_address0,
        ce0 => atanh_table_V_ce0,
        q0 => atanh_table_V_q0,
        address1 => atanh_table_V_address1,
        ce1 => atanh_table_V_ce1,
        q1 => atanh_table_V_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_22_reg_210 <= b(5 downto 5);
                tmp_reg_205 <= a(5 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_reset_start_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    abs_a_V_fu_71_p2 <= std_logic_vector(unsigned(ap_const_lv5_0) - unsigned(trunc_ln1072_fu_59_p1));
    abs_b_V_1_fu_105_p3 <= 
        abs_b_V_fu_85_p2 when (tmp_23_fu_97_p3(0) = '1') else 
        b;
    abs_b_V_2_fu_156_p3 <= 
        b when (and_ln1072_1_fu_150_p2(0) = '1') else 
        abs_b_V_fu_85_p2;
    abs_b_V_fu_85_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(b));
    add_ln232_fu_168_p2 <= std_logic_vector(unsigned(tmp_s_fu_121_p3) + unsigned(sext_ln232_fu_164_p1));
    add_ln82_fu_133_p2 <= std_logic_vector(unsigned(tmp_s_fu_121_p3) + unsigned(sext_ln82_fu_129_p1));
    and_ln1072_1_fu_150_p2 <= (xor_ln1072_fu_144_p2 and tmp_fu_63_p3);
    and_ln1072_fu_91_p2 <= (b and a);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_start_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_start_pp0 <= ap_const_logic_1;
        else 
            ap_reset_start_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        sub_ln70_fu_187_p2 when (xor_ln1072_1_fu_193_p2(0) = '1') else 
        zext_ln1072_fu_179_p1;
    atanh_table_V_address0 <= zext_ln232_fu_174_p1(10 - 1 downto 0);
    atanh_table_V_address1 <= zext_ln82_fu_139_p1(10 - 1 downto 0);

    atanh_table_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            atanh_table_V_ce0 <= ap_const_logic_1;
        else 
            atanh_table_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    atanh_table_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            atanh_table_V_ce1 <= ap_const_logic_1;
        else 
            atanh_table_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln365_fu_113_p3 <= 
        abs_a_V_fu_71_p2 when (tmp_fu_63_p3(0) = '1') else 
        trunc_ln1072_fu_59_p1;
        sext_ln232_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_b_V_2_fu_156_p3),10));

        sext_ln82_fu_129_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_b_V_1_fu_105_p3),10));

    sub_ln70_fu_187_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(zext_ln70_fu_183_p1));
    tmp_22_fu_77_p3 <= b(5 downto 5);
    tmp_23_fu_97_p3 <= and_ln1072_fu_91_p2(5 downto 5);
    tmp_fu_63_p3 <= a(5 downto 5);
    tmp_s_fu_121_p3 <= (select_ln365_fu_113_p3 & ap_const_lv5_0);
    trunc_ln1072_fu_59_p1 <= a(5 - 1 downto 0);
    xor_ln1072_1_fu_193_p2 <= (tmp_reg_205 xor tmp_22_reg_210);
    xor_ln1072_fu_144_p2 <= (tmp_22_fu_77_p3 xor ap_const_lv1_1);
    zext_ln1072_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(atanh_table_V_q1),6));
    zext_ln232_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln232_fu_168_p2),64));
    zext_ln70_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(atanh_table_V_q0),6));
    zext_ln82_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln82_fu_133_p2),64));
end behav;
