-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2.1 (64-bit)
-- Version: 2021.2.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldpcDec_colUpdate2_ch is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    l_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    l_ce0 : OUT STD_LOGIC;
    l_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    l_offset : IN STD_LOGIC_VECTOR (4 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_we0 : OUT STD_LOGIC;
    b_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    b_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    b_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    b_ce1 : OUT STD_LOGIC;
    b_we1 : OUT STD_LOGIC;
    b_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    b_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
    a_offset : IN STD_LOGIC_VECTOR (4 downto 0);
    b_offset : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of ldpcDec_colUpdate2_ch is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sub_ln555_fu_75_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln555_reg_144 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln554_fu_106_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln554_reg_149 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln232_fu_137_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln232_reg_154 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_idle : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0 : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0 : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0 : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1 : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1 : STD_LOGIC;
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_51_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_63_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln555_fu_59_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln555_1_fu_71_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_213_fu_82_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_214_fu_94_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln554_fu_90_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln554_1_fu_102_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_215_fu_113_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_216_fu_125_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_fu_121_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln232_13_fu_133_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldpcDec_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sub_ln232 : IN STD_LOGIC_VECTOR (15 downto 0);
        l_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        l_ce0 : OUT STD_LOGIC;
        l_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        sub_ln554 : IN STD_LOGIC_VECTOR (15 downto 0);
        b_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_we0 : OUT STD_LOGIC;
        b_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        b_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        b_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        b_ce1 : OUT STD_LOGIC;
        b_we1 : OUT STD_LOGIC;
        b_d1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        b_q1 : IN STD_LOGIC_VECTOR (5 downto 0);
        sub_ln555 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40 : component ldpcDec_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start,
        ap_done => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done,
        ap_idle => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_idle,
        ap_ready => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready,
        sub_ln232 => sub_ln232_reg_154,
        l_address0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0,
        l_ce0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0,
        l_q0 => l_q0,
        sub_ln554 => sub_ln554_reg_149,
        b_address0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0,
        b_ce0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0,
        b_we0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0,
        b_d0 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0,
        b_q0 => b_q0,
        b_address1 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1,
        b_ce1 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1,
        b_we1 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1,
        b_d1 => grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1,
        b_q1 => b_q1,
        sub_ln555 => sub_ln555_reg_144);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_ready = ap_const_logic_1)) then 
                    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    sub_ln232_reg_154(15 downto 6) <= sub_ln232_fu_137_p2(15 downto 6);
                    sub_ln554_reg_149(15 downto 6) <= sub_ln554_fu_106_p2(15 downto 6);
                    sub_ln555_reg_144(15 downto 6) <= sub_ln555_fu_75_p2(15 downto 6);
            end if;
        end if;
    end process;
    sub_ln555_reg_144(5 downto 0) <= "000000";
    sub_ln554_reg_149(5 downto 0) <= "000000";
    sub_ln232_reg_154(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done)
    begin
        if ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_address0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address0;
    b_address1 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_address1;
    b_ce0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce0;
    b_ce1 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_ce1;
    b_d0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d0;
    b_d1 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_d1;
    b_we0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we0;
    b_we1 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_b_we1;
    grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_ap_start_reg;
    l_address0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_address0;
    l_ce0 <= grp_colUpdate2_ch_Pipeline_VITIS_LOOP_551_1_fu_40_l_ce0;
    sub_ln232_fu_137_p2 <= std_logic_vector(unsigned(zext_ln232_fu_121_p1) - unsigned(zext_ln232_13_fu_133_p1));
    sub_ln554_fu_106_p2 <= std_logic_vector(unsigned(zext_ln554_fu_90_p1) - unsigned(zext_ln554_1_fu_102_p1));
    sub_ln555_fu_75_p2 <= std_logic_vector(unsigned(zext_ln555_fu_59_p1) - unsigned(zext_ln555_1_fu_71_p1));
    tmp_213_fu_82_p3 <= (a_offset & ap_const_lv10_0);
    tmp_214_fu_94_p3 <= (a_offset & ap_const_lv6_0);
    tmp_215_fu_113_p3 <= (l_offset & ap_const_lv10_0);
    tmp_216_fu_125_p3 <= (l_offset & ap_const_lv6_0);
    tmp_fu_51_p3 <= (b_offset & ap_const_lv10_0);
    tmp_s_fu_63_p3 <= (b_offset & ap_const_lv6_0);
    zext_ln232_13_fu_133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_216_fu_125_p3),16));
    zext_ln232_fu_121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_215_fu_113_p3),16));
    zext_ln554_1_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_214_fu_94_p3),16));
    zext_ln554_fu_90_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_213_fu_82_p3),16));
    zext_ln555_1_fu_71_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_63_p3),16));
    zext_ln555_fu_59_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_51_p3),16));
end behav;
